eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/
server:
  port: 8082

spring:
  application:
    name: security-service
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Restaurant
          jwk-set-uri: http://localhost:8080/realms/Restaurant/protocol/openid-connect/certs
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: '::::::::::::  ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/securitykeycloakOns
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

email:
  url: http://localhost:9090/api/mail

keycloak:
  server-url: "http://localhost:8080"
  realm: "Restaurant"
  client-id: "keycloakRestaurant"
  client-secret: "FJ49Gy7gInUOz0OIZCPeBXPdZNzrp2Lh"
  admin-username: "One.wersighni@esprit.tn"
  admin-password: "ons12345"
  lock-duration: 30